import { Geist, Geist_Mono } from "next/font/google";
import localFont from 'next/font/local'
import "../globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";

const sfPro = localFont({
    src: [
        {
            path: '../fonts/SFProDisplay-Regular.ttf',
            weight: '400',
            style: 'normal',
        },
        {
            path: '../fonts/SFProDisplay-RegularItalic.ttf',
            weight: '400',
            style: 'italic',
        },
        {
            path: '../fonts/SFProDisplay-Bold.ttf',
            weight: '700',
            style: 'normal',
        },
        {
            path: '../fonts/SFProDisplay-BoldItalic.ttf',
            weight: '700',
            style: 'italic',
        },
    ],
})

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`${sfPro.variable} ${geistMono.variable} antialiased`} suppressHydrationWarning={true}>
                {children}
            </body>
        </html>
    );
}
